### ISSUE TITLE
Topbar links don't work

### ISSUE THREAD

**Issue by stof** [apigen/apigen.github.io#2]
Clicking on the link to the github account has no effect for instance

**Comment by stof** [comment]
The issue is https://github.com/apigen/apigen.github.io/blob/9d0a93e5dd61a827beae9ed87af623ec9de8b9b8/resources/script.js#L5 which prevents the default for external links too

**Comment by TomasVotruba** [comment]
@stof Thanks for reporting. I missed this issue. Could you send PR pls?
